/**
 * One-time desktop OAuth flow — `pnpm google:auth`.
 *
 * Run it on the Mac, once. It opens the consent screen, catches the callback on
 * a loopback port and writes `google.env` (mode 0600) with the refresh token.
 * That file is then copied to the box; the server never runs a browser flow.
 *
 * Nothing here is executed by tests: only the pure helpers below are.
 */
import { spawn } from 'node:child_process';
import http from 'node:http';
import fs from 'node:fs';
import type { AddressInfo } from 'node:net';
import { google } from 'googleapis';
import { SCOPES } from './scopes.js';

export interface ClientSecret {
  clientId: string;
  clientSecret: string;
}

export interface EnvValues extends ClientSecret {
  refreshToken: string;
  ownerEmail: string;
}

/** Read a Google `client_secret_*.json` (desktop or web shape). */
export function parseClientSecretFile(json: string): ClientSecret {
  let parsed: unknown;
  try {
    parsed = JSON.parse(json);
  } catch {
    throw new Error('client secret file is not valid JSON');
  }
  if (typeof parsed !== 'object' || parsed === null) {
    throw new Error('client secret file is not an object');
  }
  const root = parsed as Record<string, unknown>;
  const section = (root['installed'] ?? root['web']) as Record<string, unknown> | undefined;
  if (section === undefined) {
    throw new Error('client secret file has neither an "installed" nor a "web" section');
  }
  const clientId = section['client_id'];
  const clientSecret = section['client_secret'];
  if (typeof clientId !== 'string' || clientId === '') {
    throw new Error('client secret file has no client_id');
  }
  if (typeof clientSecret !== 'string' || clientSecret === '') {
    throw new Error('client secret file has no client_secret');
  }
  return { clientId, clientSecret };
}

/** The contents of `google.env`. */
export function renderGoogleEnv(values: EnvValues, now: Date = new Date()): string {
  const stamp = now.toISOString().slice(0, 10);
  return [
    `# Generated by \`pnpm google:auth\` on ${stamp}. Mode 0600, never commit it.`,
    "# Copy to the box: scp google.env root@cxw:/srv/cxw/google.env && ssh root@cxw 'chmod 0600 /srv/cxw/google.env'",
    `GOOGLE_CLIENT_ID=${values.clientId}`,
    `GOOGLE_CLIENT_SECRET=${values.clientSecret}`,
    `GOOGLE_REFRESH_TOKEN=${values.refreshToken}`,
    `GOOGLE_OWNER_EMAIL=${values.ownerEmail}`,
    '',
  ].join('\n');
}

/** Pull `code` or `error` out of the loopback callback request URL. */
export function parseCallbackUrl(url: string): { code: string } | { error: string } {
  let parsed: URL;
  try {
    parsed = new URL(url, 'http://127.0.0.1');
  } catch {
    return { error: 'unparseable callback URL' };
  }
  const error = parsed.searchParams.get('error');
  if (error !== null && error !== '') return { error };
  const code = parsed.searchParams.get('code');
  if (code !== null && code !== '') return { code };
  return { error: 'callback carried neither code nor error' };
}

/** Minimal `--flag value` / `--flag` parser for this script's arguments. */
export function parseArgs(argv: string[]): Record<string, string | boolean> {
  const out: Record<string, string | boolean> = {};
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === undefined || !arg.startsWith('--')) continue;
    const key = arg.slice(2);
    const next = argv[i + 1];
    if (next !== undefined && !next.startsWith('--')) {
      out[key] = next;
      i += 1;
    } else {
      out[key] = true;
    }
  }
  return out;
}

function openInBrowser(url: string): void {
  const cmd = process.platform === 'darwin' ? 'open' : 'xdg-open';
  try {
    spawn(cmd, [url], { stdio: 'ignore', detached: true }).unref();
  } catch {
    // Printing the URL is always the fallback.
  }
}

async function waitForCode(server: http.Server): Promise<string> {
  return new Promise<string>((resolve, reject) => {
    server.on('request', (req, res) => {
      const result = parseCallbackUrl(req.url ?? '');
      const done = 'code' in result;
      res.writeHead(done ? 200 : 400, { 'content-type': 'text/plain; charset=utf-8' });
      res.end(
        done
          ? 'Authorised. You can close this tab and go back to the terminal.'
          : `Authorisation failed: ${'error' in result ? result.error : 'unknown'}`,
      );
      if ('code' in result) resolve(result.code);
      else reject(new Error(result.error));
    });
  });
}

export async function main(argv: string[] = process.argv.slice(2)): Promise<number> {
  const args = parseArgs(argv);
  const out = typeof args['out'] === 'string' ? args['out'] : './google.env';
  const force = args['force'] === true;
  if (fs.existsSync(out) && !force) {
    console.error(`${out} already exists. Re-run with --force to overwrite it.`);
    return 1;
  }

  let creds: ClientSecret;
  const secretPath = args['client-secret'];
  if (typeof secretPath === 'string') {
    creds = parseClientSecretFile(fs.readFileSync(secretPath, 'utf8'));
  } else {
    const clientId = process.env['GOOGLE_CLIENT_ID'] ?? '';
    const clientSecret = process.env['GOOGLE_CLIENT_SECRET'] ?? '';
    if (clientId === '' || clientSecret === '') {
      console.error(
        'Pass --client-secret <client_secret_*.json> (Google Cloud → APIs & Services → ' +
          'Credentials → OAuth client of type "Desktop app"), or set GOOGLE_CLIENT_ID and ' +
          'GOOGLE_CLIENT_SECRET. See docs/RUNBOOK.md §8.',
      );
      return 2;
    }
    creds = { clientId, clientSecret };
  }

  const server = http.createServer();
  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
  const port = (server.address() as AddressInfo).port;
  const redirectUri = `http://127.0.0.1:${port}/oauth2callback`;
  const oauth2 = new google.auth.OAuth2({
    clientId: creds.clientId,
    clientSecret: creds.clientSecret,
    redirectUri,
  });
  const url = oauth2.generateAuthUrl({
    access_type: 'offline',
    prompt: 'consent',
    scope: [...SCOPES],
  });

  console.log(`Open this URL and grant access:\n\n${url}\n`);
  if (args['no-open'] !== true) openInBrowser(url);

  let code: string;
  try {
    code = await waitForCode(server);
  } finally {
    server.close();
  }

  const { tokens } = await oauth2.getToken(code);
  const refreshToken = tokens.refresh_token ?? '';
  if (refreshToken === '') {
    console.error(
      'Google returned no refresh token. Revoke the app at ' +
        'https://myaccount.google.com/permissions and run this again.',
    );
    return 1;
  }
  oauth2.setCredentials(tokens);

  const gmail = google.gmail({ version: 'v1', auth: oauth2 });
  const profile = await gmail.users.getProfile({ userId: 'me' });
  const ownerEmail = profile.data.emailAddress ?? '';
  if (ownerEmail === '') {
    console.error('Could not read the account e-mail address from Gmail.');
    return 1;
  }

  const text = renderGoogleEnv({ ...creds, refreshToken, ownerEmail });
  fs.writeFileSync(out, text, { mode: 0o600 });
  fs.chmodSync(out, 0o600);

  console.log(
    [
      '',
      `Wrote ${out} (0600) for ${ownerEmail}.`,
      '',
      'Next:',
      `  scp ${out} root@cxw:/srv/cxw/google.env`,
      "  ssh root@cxw 'chmod 0600 /srv/cxw/google.env && systemctl restart cxw-brain'",
      '',
      'IMPORTANT: publish the OAuth consent screen to Production. While it is in',
      'Testing, Google expires refresh tokens after 7 days and the assistant loses',
      'Gmail and Calendar without saying anything.',
    ].join('\n'),
  );
  return 0;
}

const entry = process.argv[1];
if (entry !== undefined && import.meta.url === new URL(`file://${entry}`).href) {
  main()
    .then((code) => {
      process.exitCode = code;
    })
    .catch((err: unknown) => {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    });
}
