import { describe, expect, it } from 'vitest';
import { parseArgs, parseCallbackUrl, parseClientSecretFile, renderGoogleEnv } from './auth.js';

describe('parseClientSecretFile', () => {
  it('reads the desktop ("installed") shape', () => {
    const json = JSON.stringify({
      installed: { client_id: 'id-1.apps.googleusercontent.com', client_secret: 'sec-1' },
    });
    expect(parseClientSecretFile(json)).toEqual({
      clientId: 'id-1.apps.googleusercontent.com',
      clientSecret: 'sec-1',
    });
  });

  it('reads the "web" shape too', () => {
    const json = JSON.stringify({ web: { client_id: 'id-2', client_secret: 'sec-2' } });
    expect(parseClientSecretFile(json)).toEqual({ clientId: 'id-2', clientSecret: 'sec-2' });
  });

  it('explains what is wrong', () => {
    expect(() => parseClientSecretFile('not json')).toThrow(/valid JSON/u);
    expect(() => parseClientSecretFile('{}')).toThrow(/"installed".*"web"/u);
    expect(() => parseClientSecretFile(JSON.stringify({ installed: {} }))).toThrow(/client_id/u);
    expect(() => parseClientSecretFile(JSON.stringify({ installed: { client_id: 'a' } }))).toThrow(
      /client_secret/u,
    );
  });
});

describe('renderGoogleEnv', () => {
  it('writes the four variables other phases read', () => {
    const text = renderGoogleEnv(
      {
        clientId: 'id-1',
        clientSecret: 'sec-1',
        refreshToken: 'refresh-1',
        ownerEmail: 'me@example.com',
      },
      new Date('2026-09-04T09:00:00Z'),
    );
    expect(text).toContain('# Generated by `pnpm google:auth` on 2026-09-04.');
    expect(text).toContain('scp google.env root@cxw:/srv/cxw/google.env');
    expect(text).toContain('GOOGLE_CLIENT_ID=id-1\n');
    expect(text).toContain('GOOGLE_CLIENT_SECRET=sec-1\n');
    expect(text).toContain('GOOGLE_REFRESH_TOKEN=refresh-1\n');
    expect(text).toContain('GOOGLE_OWNER_EMAIL=me@example.com\n');
    expect(text.endsWith('\n')).toBe(true);
  });
});

describe('parseCallbackUrl', () => {
  it('extracts the code', () => {
    expect(parseCallbackUrl('/oauth2callback?code=4/abc&scope=x')).toEqual({ code: '4/abc' });
  });

  it('extracts the error', () => {
    expect(parseCallbackUrl('/oauth2callback?error=access_denied')).toEqual({
      error: 'access_denied',
    });
  });

  it('reports a callback with neither', () => {
    expect(parseCallbackUrl('/favicon.ico')).toEqual({
      error: 'callback carried neither code nor error',
    });
  });
});

describe('parseArgs', () => {
  it('reads flags with and without values', () => {
    expect(parseArgs(['--client-secret', '/tmp/cs.json', '--force', '--out', 'g.env'])).toEqual({
      'client-secret': '/tmp/cs.json',
      force: true,
      out: 'g.env',
    });
    expect(parseArgs([])).toEqual({});
  });
});
