/**
 * The cloud-init payload, and the leak guard that both payload builders run.
 *
 * Browser-safe: no `node:` imports and no filesystem access. The page itself renders
 * the payload for the "any other server" path, so this must load in a browser.
 *
 * `CLOUD_INIT_TEMPLATE` below is a byte-for-byte copy of `cloud-init.template.yml`,
 * which stays on disk as the readable reference. `cloud-init.ts` reads that file and
 * `cloud-init.test.ts` fails if the two ever drift.
 */

import { toBase64 } from './ssh-key.js';

export const CLOUD_INIT_TEMPLATE = `#cloud-config
# ClaudeXWhatsapp — installer payload, generated by apps/installer (phase 10).
#
# Hetzner shows a server's user-data in its own console by design, so treat this
# document as sensitive. deploy/hetzner/bootstrap.sh shreds the on-disk copy on
# first boot, guarded by a stamp file so a re-run does not fail.
#
# Every secret in here is carried as base64 (encoding b64) so nothing has to be
# YAML-quoted and no secret can appear in a shell word or a log line.

package_update: true
packages:
  - ca-certificates
  - curl
  - git

write_files:
  - path: /root/.ssh/cxw_deploy
    owner: 'root:root'
    permissions: '0600'
    encoding: b64
    content: __DEPLOY_KEY_PRIVATE_B64__
  - path: /root/.ssh/cxw_deploy.pub
    owner: 'root:root'
    permissions: '0644'
    encoding: b64
    content: __DEPLOY_KEY_PUBLIC_B64__
  - path: /root/cxw-installer.env
    owner: 'root:root'
    permissions: '0600'
    encoding: b64
    content: __INSTALLER_ENV_B64__

runcmd:
  # 1. the deploy key, for the unprivileged cxw user that owns the checkout
  - install -d -m 0700 -o root -g root /root/.ssh
  - id -u cxw >/dev/null 2>&1 || useradd --system --create-home --home-dir /home/cxw --shell /bin/bash cxw
  - install -d -m 0700 -o cxw -g cxw /home/cxw/.ssh
  - install -m 0600 -o cxw -g cxw /root/.ssh/cxw_deploy /home/cxw/.ssh/cxw_deploy
  # 2. github's host keys, so git is not prompted and does not trust on first use
  - ssh-keyscan -t rsa,ecdsa,ed25519 github.com >> /home/cxw/.ssh/known_hosts
  - chown cxw:cxw /home/cxw/.ssh/known_hosts && chmod 0600 /home/cxw/.ssh/known_hosts
  # 3. the checkout
  - install -d -m 0711 -o root -g root /srv/cxw
  - install -d -m 0700 -o cxw -g cxw /srv/cxw/repo
  - sudo -u cxw -H git -c core.sshCommand='ssh -i /home/cxw/.ssh/cxw_deploy -o IdentitiesOnly=yes' clone --branch '__BRANCH__' '__REPO_URL__' /srv/cxw/repo
  - sudo -u cxw -H git -C /srv/cxw/repo config core.sshCommand 'ssh -i /home/cxw/.ssh/cxw_deploy -o IdentitiesOnly=yes'
  # 4. bootstrap, with the installer's variables exported from the base64 fragment
  - set -a && . /root/cxw-installer.env && set +a && bash /srv/cxw/repo/deploy/hetzner/bootstrap.sh
`;

/** The loopback address and port the Cloudflare tunnel's ingress points at. */
export const CONSOLE_HOST = '127.0.0.1';
export const CONSOLE_PORT = 7803;

/** Paths whose base64 `content:` may legitimately carry a secret. */
const SECRET_FILE_PATHS: readonly string[] = ['/root/.ssh/cxw_deploy', '/root/cxw-installer.env'];

export interface CloudInitInput {
  readonly repoUrl: string;
  readonly branch: string;
  readonly deployKeyPrivate: string;
  readonly deployKeyPublic: string;
  readonly tailscaleAuthKey?: string | undefined;
  readonly tunnelToken: string;
  readonly accessTeam: string;
  readonly accessAud: string;
  readonly consoleHostname: string;
  readonly timezone: string;
  readonly ownerEmail: string;
}

export class CloudInitLeakError extends Error {
  readonly leaked: readonly string[];

  constructor(leaked: readonly string[]) {
    super(
      `payload leaks ${leaked.length} secret(s) outside the allowed anchors: ${leaked.join(', ')}. ` +
        `A secret may only appear inside the base64 content for ${SECRET_FILE_PATHS.join(' or ')}, ` +
        `inside a declared base64 blob, or inside a "tailscale up" command.`,
    );
    this.name = 'CloudInitLeakError';
    this.leaked = leaked;
  }
}

/**
 * Blank the regions where a secret is allowed, then look for every secret in what is
 * left. Anything found there is a leak: it would end up in a shell word, a log line
 * or a cloud-init status file.
 *
 * `extraAnchors` lets a non-YAML payload (the SSH one-liner) declare the exact base64
 * blobs it embeds, so the same guard covers it.
 */
export function assertNoSecretLeaks(
  rendered: string,
  secrets: Record<string, string>,
  extraAnchors: readonly string[] = [],
): void {
  let text = rendered;
  for (const anchor of extraAnchors) {
    if (anchor !== '') text = text.split(anchor).join('<blanked blob>');
  }

  const lines = text.split('\n');
  let currentPath: string | null = null;

  const blanked = lines.map((line) => {
    const pathMatch = /^\s*-\s*path:\s*(\S+)\s*$/.exec(line);
    if (pathMatch !== null) {
      currentPath = pathMatch[1] ?? null;
      return line;
    }
    // Anchor 1 and 2: the base64 blobs destined for cxw.env and the deploy key.
    const contentMatch = /^(\s*content:\s*)(\S+)\s*$/.exec(line);
    if (contentMatch !== null && currentPath !== null && SECRET_FILE_PATHS.includes(currentPath)) {
      return `${contentMatch[1] ?? ''}<blanked>`;
    }
    // Anchor 3: the Tailscale join command, whose key cannot be passed as a file.
    if (/\btailscale\s+up\b/.test(line)) return '<blanked tailscale up>';
    return line;
  });

  const remainder = blanked.join('\n');
  const leaked: string[] = [];
  for (const [name, value] of Object.entries(secrets)) {
    if (value === '') continue;
    if (remainder.includes(value)) leaked.push(name);
  }
  if (leaked.length > 0) throw new CloudInitLeakError(leaked);
}

/** The secrets both payload builders guard. */
export function payloadSecrets(input: CloudInitInput): Record<string, string> {
  return {
    deployKeyPrivate: input.deployKeyPrivate,
    tunnelToken: input.tunnelToken,
    accessAud: input.accessAud,
    ...(input.tailscaleAuthKey === undefined ? {} : { tailscaleAuthKey: input.tailscaleAuthKey }),
  };
}

const SAFE_BRANCH = /^[A-Za-z0-9._\-/]{1,200}$/;
const SAFE_REPO_URL = /^(?:git@[A-Za-z0-9.-]+:[A-Za-z0-9._\-/]+\.git|https:\/\/[A-Za-z0-9.\-/_]+)$/;
const SAFE_HOSTNAME = /^[A-Za-z0-9.-]{1,253}$/;
const SAFE_TIMEZONE = /^[A-Za-z0-9+_\-/]{1,64}$/;

/** Refuse anything that could break out of a YAML scalar or a shell word. */
export function assertSafeInput(input: CloudInitInput): void {
  if (!SAFE_REPO_URL.test(input.repoUrl)) throw new Error(`refusing to template an unusual repo URL: ${input.repoUrl}`);
  if (!SAFE_BRANCH.test(input.branch)) throw new Error(`refusing to template an unusual branch: ${input.branch}`);
  if (!SAFE_HOSTNAME.test(input.consoleHostname)) {
    throw new Error(`refusing to template an unusual hostname: ${input.consoleHostname}`);
  }
  if (!SAFE_TIMEZONE.test(input.timezone)) throw new Error(`refusing to template an unusual timezone: ${input.timezone}`);
}

export function utf8ToBase64(text: string): string {
  return toBase64(new TextEncoder().encode(text));
}

/** The KEY=VALUE fragment bootstrap.sh sources and merges into /srv/cxw/cxw.env. */
export function buildInstallerEnv(input: CloudInitInput): string {
  const lines = [
    '# Written by the ClaudeXWhatsapp installer (phase 10). Sourced once by bootstrap.sh.',
    `CXW_TUNNEL_TOKEN=${input.tunnelToken}`,
    'CXW_SETUP_MODE=1',
    `CXW_CONSOLE_HOSTNAME=${input.consoleHostname}`,
    `CF_ACCESS_TEAM=${input.accessTeam}`,
    `CF_ACCESS_AUD=${input.accessAud}`,
    'CONSOLE_REQUIRE_ACCESS=true',
    `CONSOLE_HOST=${CONSOLE_HOST}`,
    `CONSOLE_PORT=${CONSOLE_PORT}`,
    `TZ=${input.timezone}`,
    `CXW_TIMEZONE=${input.timezone}`,
    `CXW_OWNER_EMAIL=${input.ownerEmail}`,
  ];
  if (input.tailscaleAuthKey !== undefined && input.tailscaleAuthKey !== '') {
    lines.push(`TS_AUTHKEY=${input.tailscaleAuthKey}`);
  }
  return `${lines.join('\n')}\n`;
}

export function buildCloudInit(input: CloudInitInput, template: string = CLOUD_INIT_TEMPLATE): string {
  assertSafeInput(input);

  const rendered = template
    .replaceAll('__DEPLOY_KEY_PRIVATE_B64__', utf8ToBase64(input.deployKeyPrivate))
    .replaceAll('__DEPLOY_KEY_PUBLIC_B64__', utf8ToBase64(input.deployKeyPublic))
    .replaceAll('__INSTALLER_ENV_B64__', utf8ToBase64(buildInstallerEnv(input)))
    .replaceAll('__REPO_URL__', input.repoUrl)
    .replaceAll('__BRANCH__', input.branch);

  if (!rendered.startsWith('#cloud-config')) throw new Error('cloud-init payload must begin with #cloud-config');
  const leftover = /__[A-Z0-9_]+__/.exec(rendered);
  if (leftover !== null) throw new Error(`cloud-init template placeholder left unfilled: ${leftover[0]}`);

  assertNoSecretLeaks(rendered, payloadSecrets(input));
  return rendered;
}
